import { createElement } from "lwc";
import OppTeamList from "c/oppTeamList";
import { registerApexTestWireAdapter } from "@salesforce/sfdx-lwc-jest";
import getTeamMembers from "@salesforce/apex/OppTeamListController.getTeamMembers";

const getTeamMembersAdapter = registerApexTestWireAdapter(getTeamMembers);

// Helper to generate team member records
function generateMembers(count) {
  return Array.from({ length: count }, (_, i) => ({
    Id: `00${i}`,
    TeamMemberRole: "Account Manager",
    User: { Name: `User ${i}`, CompanyName: "ACME" }
  }));
}

describe("c-opp-team-list", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-opp-team-list", {
      is: OppTeamList
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });

  it("renders scrollable container around datatable", async () => {
    const element = createElement("c-opp-team-list", { is: OppTeamList });
    document.body.appendChild(element);

    getTeamMembersAdapter.emit(generateMembers(5));
    await Promise.resolve();

    const container = element.shadowRoot.querySelector(
      ".scrollable-table-container"
    );
    expect(container).not.toBeNull();
  });

  it("initially shows only the first page of team members (PAGE_SIZE = 10)", async () => {
    const element = createElement("c-opp-team-list", { is: OppTeamList });
    document.body.appendChild(element);

    getTeamMembersAdapter.emit(generateMembers(25));
    await Promise.resolve();

    const datatable = element.shadowRoot.querySelector("lightning-datatable");
    expect(datatable).not.toBeNull();
    expect(datatable.data.length).toBe(10);
  });

  it("loads more rows when handleLoadMore is triggered", async () => {
    const element = createElement("c-opp-team-list", { is: OppTeamList });
    document.body.appendChild(element);

    getTeamMembersAdapter.emit(generateMembers(25));
    await Promise.resolve();

    const datatable = element.shadowRoot.querySelector("lightning-datatable");
    expect(datatable.data.length).toBe(10);

    // Simulate loadmore event
    datatable.dispatchEvent(new CustomEvent("loadmore"));
    await Promise.resolve();

    expect(datatable.data.length).toBe(20);
  });

  it("disables infinite loading when all rows are shown", async () => {
    const element = createElement("c-opp-team-list", { is: OppTeamList });
    document.body.appendChild(element);

    getTeamMembersAdapter.emit(generateMembers(5));
    await Promise.resolve();

    const datatable = element.shadowRoot.querySelector("lightning-datatable");
    expect(datatable.data.length).toBe(5);

    datatable.dispatchEvent(new CustomEvent("loadmore"));
    await Promise.resolve();

    // All 5 records already loaded – enableInfiniteLoading should be set to false on the datatable
    expect(datatable.enableInfiniteLoading).toBe(false);
  });
});
